[general]
# 监听地址
listen = "0.0.0.0:8000"

[logger]
# 日志级别 DEBUG > INFO > WARN > ERROR
# debug = true|false 对应日志级别 DEBUG|INFO
debug = true
# 日志文件目录
directory = "./log"
# 日志文件前缀
file_name_prefix = "silk.log"

[database]
# url = "postgres://username:password@host/database"
url = "postgres://username:password@host/database"
# 连接池最大连接数（默认10）
max_connections = 10
# 连接池最小连接数（默认0）
min_connections = 0
# 连接池等待获取数据库连接的最大时间（默认30s）
acquire_timeout = 30
# 连接池最大空闲时间（默认600s）
idle_timeout = 600
# 连接池最大生命周期（默认1800s）
max_lifetime = 1800

[redis]
# url = "redis://[<username>][:<password>@]<hostname>[:port][/<db>]"
url = "redis://127.0.0.1:6379"
